name: Build Page

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: NPM Install
        run: npm ci
      - name: Setup Angular
        run: npm install @angular/cli
      - name: Build
        run: npm run build
      - name: move folder 1 up
        run: mv dist/vl-big-blocks-schichtplanung/* dist/ && rm -r dist/vl-big-blocks-schichtplanung/
      - name: tar dist Artifact
        run: tar -cvf dist.tar dist/
      - name: Safe dist Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: dist
          path: dist.tar
  pages:
    name: Create Github Page
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download dist
      uses: actions/download-artifact@v2.0.5
      with:
        name: dist
        path: ./
    - name: Untar dist
      run: tar -xvf dist.tar
    - name: Change Basepath in index.html
      run: sed -i 's/<base href="\/">/<base href="\/vlbb\/">/g' dist/index.html
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: dist/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 